/**
 * E2E Test Report Type Definitions
 *
 * Defines the structure for test results and reports generated by the QA agent.
 */

export interface StepResult {
  stepIndex: number;
  description: string;
  action: string;
  status: 'passed' | 'failed' | 'skipped';
  duration: number; // ms
  error?: {
    message: string;
    expected?: string;
    actual?: string;
  };
  screenshot?: string; // Path to screenshot if taken
}

export interface ScenarioResult {
  id: string;
  name: string;
  status: 'passed' | 'failed' | 'skipped';
  duration: number; // ms
  steps: StepResult[];
  errorScreenshot?: string; // Screenshot on failure
}

export interface TestReport {
  runId: string;
  timestamp: string;
  duration: number; // ms
  summary: {
    total: number;
    passed: number;
    failed: number;
    skipped: number;
  };
  scenarios: ScenarioResult[];
  environment: {
    frontendUrl: string;
    backendUrl: string;
    nodeVersion?: string;
    platform?: string;
  };
}
